dist: xenial
language: python
python: 3.7
cache:
  pip: true
install:
- pip install -r requirements.txt
script: "./manage.py compilemessages_ci"
before_deploy: "./archive.sh"
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: donate-wagtail-translations
  local_dir: to_upload
  skip_cleanup: true
  acl: public_read
env:
  global:
  - ALLOWED_HOSTS=localhost
  - DEBUG=False
  - SECRET_KEY=secret
  - secure: DVvTQKhO80vVjX6dBTYYGx4nivaakm/1ASQgC7LpRta54d41rCL0aopbSl7A0I/Y+NwsY8VqalcS9E4DwR6QYaELYWiEGrdwPsRCQvBXD54/FB45kfgqKqPxJPbZHyAXLLYbM32x1JL6SjRdKhPozlburIX1Tz52srw9xz0KqKrFw0d1oejBVNX6pImoAM3Y6P6GJVkrJaWBD9qcWk7KqAtWvSU7NANfgfQUkGp0eQchxFbBUzNccRXLOpIqe65pFbR0KvgaJNc9wlRKvAWq1wGR+fJ2FmT9ttuqf2yAwLe6bRH60dgWPLLZHQUmoauQ6sb18OxgiLv9jcKWHFFYxXBfk1qwcQt/HshuLzR0T411/9V2zJFfT0gJr9mNmARURvQXJndLhv/r803/XYPy8ksFGejNp538syjIFmPEj+pW/EBWJe8tUCks1hrTVLJIXLa97mX6dG9W4Yjz28YBSgV9NgQGUlrtkjCYNl9pLYrI843VwyBnA3qoUL8kaizpLp56iddWdN9q9cPXefGow6n41JGf5wqTyJpNUOU+a6PWydhw071wk9QPsgzG1Y0SI7Gp7gABI1G7a3bfTQys8bwT41pk9tuT+T/zsUAefnlum/260HORGzl2XNP3W19ZhbQdEEr6b/TRjAeGUI70w61J6qX+oN0tzC+XygNaGPE=
  - secure: PkYUnjOvMuKcTfeP5m+zGBNbjp3xCMCi159lCObRwWIBRSpzvhtNx9pnyAKqYhPZ9FeSd0L50s4IlTZT9JILuUaVrAO70Ncz1+AkjzKbt5LjPLnss9F5QrXBvP7Gm0RgL4Vf3ttk82up1zy/mmguimYbJMvQVn2BN6w9YDJAjVtOJ+EJFlt43X7uHr9Wgdop6qTF3kuA+2T4fVnr1JOKTMis6Y5ygzOPyR6COIo4VT8RpSw5iaWJzaZuXHlgwPqSkAedyeqFqkoB8PcJ5xvPBBBy/hg7zCaE+mZMnmCqLqxpF15DOlvmOBl9X8dTiClviPHPKbZ7sK2Ucmr6esyyglD8fXu30cpRaOoWYosBbEktd/ModBWT23/ldYz5ewFNfWysNABjh7DAH4ldQo6w3yvwkSi5uObehQjbep0aIoZpAR+bzHA1DSt4rwPfjA3Jn8iXYMn7xsvELM+VFxkzehxvN0TZC1A7O70RiD4EBl8HzuvumG1byNTXNB1rdAWM14fnuUD/P1idJHLITsBhi0Yfd766IA66sPw+qp4ZRMFa2HbzDFPjo/4gph3oY9pqC7cmcgDxYIuUqC2m866OBT3GFeuDabsOGz6wggi9uaLIDjG0eQtRtfXkb+pdtFkdYCUWgIIMT9He9CvHzl50onoXrPSNAJ+Z2iUx+xIji4A=
  - secure: Cayb4J+qmdi1ytLKT5V9Yt2E8BME7TcwpjSHqUHtF7U+73TXLZYGWpB68m2boNZbR7xz/7lCoUQlDa5sOgjhyZ6hEyvHUguxcHsPf6iqYmiAl/hIc9bvUlgfuHCQT+G0gON0jK4zeiOgZSQLcv001q0Tc/ZVXbMwpkhyby3roihUGv9oc6ESRTRgitJm2knJmkeFdD9pY112R3TkHA9r37CoCqAmWQTiu2cQN1/0sp+qkMrLcmybLb5KlU1W1/onYyHHk2btU7sT9FwoMbZ7FrUJgst+s7OiGNYF4lpfZvn7SFFRljlBwMJS/0OYrYCLM7S0CMl4efIhq+1TUD/8i7Vod1IxSOYmUvinJROW2PKzZdLonl+8TSDPtm3LzJSP0yx4YkOIEjL/8IUXe0KGFsWDhc5foT1+7nGedhjiH5M0pfexMm6zehXe7QWyPoFfploB36N4eLpyh5IHP0Xi9LWhxnPyLbx2yW3AmFuwKlPLaLlVqFggmz9A/jHD24dIK8vmlMdAARexCJKJWd4nvTBG1Ha1hZBhbgsIgFz5FjvTExUOtf/zdOZW7WLjwPKmCA55jHJd7jHE21237ARzbhkView36BpAiwo/hLFpo8b+wDv2qYrQQsI9+XUghuIqaJB9BVub/p2OHMfNv0kpiIQ3U76Y1L/NU0h7Nog+Cow=
